### ISSUE TITLE
multiplication by a small constant

### ISSUE THREAD

**Issue by aviziskind** [tinghuiz/SfMLearner#101]
In the nets.py, in the calculation of pose, you multiply by a small constant of 0.01:

```
                # Empirically we found that scaling by a small constant 
                # facilitates training.
                pose_final = 0.01 * tf.reshape(pose_avg, [-1, num_source, 6])

```

I am curious how you came to discover this... and if you have any intuition as to why this should help to facilitate training?

**Comment by tinghuiz** [comment]
The intuition was that since we are sampling consecutive frames, the pose change should be relatively small. So multiplying by a small constant incorporates such prior information.
