### ISSUE TITLE
Pose evaluation code and multi GPU training

### ISSUE THREAD

**Issue by asiron** [tinghuiz/SfMLearner#11]
First of all, thanks a lot for releasing the code, the paper is amazing!

I just wanted to ask, when are you planning on releasing the evaluation code and whether you're planning on adding multi-GPU training as well.

Cheers,
Maciej

**Comment by jeongc** [comment]
Hi, 
I am also waiting for POSE evaluation codes. Meanwhile, I am wondering why you fixed the length of input image sequence to your system as 5? I am really curious about result of long image sequence. 
Could you share this kind of results also?
Thanks for in advance.

CJ

**Comment by tinghuiz** [comment]
I'll see if I can manage to squeeze out some time this weekend to release the pose evaluation code. No promises though... 

@jeongc I didn't try longer sequences as significant portion of the image will no longer be visible in all the frames, and thus the view synthesis loss would not be very meaningful.

**Comment by tinghuiz** [comment]
Pose evaluation and testing code has been released.
