### ISSUE TITLE
How to find the define for the funtion projective_inverse_warp ?

### ISSUE THREAD

**Issue by royal-feng** [tinghuiz/SfMLearner#18]
hello, The research is great work in monocular depth and camera motion estimation!
I read most of your code in SfMlearner.py, but I can not find the function projective_inverse_warp at SfMlearner.py  line-67#. could you tell me how to find it? I think it's the key to understand the formulation-2 in your paper!

**Comment by yzcjtr** [comment]
find it in utils.py

**Comment by royal-feng** [comment]
The function inverse_warp in the utils.py ,is equal to projective_inverse_warp ?

**Comment by tinghuiz** [comment]
`inverse_warp` has been updated to `projective_inverse_warp` in a recent commit for better readability.
