### ISSUE TITLE
Error when run this code on jupyter  notebook

### ISSUE THREAD

**Issue by TimingSpace** [tinghuiz/SfMLearner#2]
I have read your relative paper and believe this work will a great one. When I try your code on jupyter notebook with ubuntu 16.04, tensorflow. I encounter an error:

TypeError: concat() got an unexpected keyword argument 'axis' 

the details are as following
%pylab inline
from __future__ import division
import os
import numpy as np
import scipy.misc
import tensorflow as tf
from SfMLearner import SfMLearner
from utils import *
​
mode = 'depth'
img_height=128
img_width=416
ckpt_file = 'models/model-145248'
I = scipy.misc.imread('misc/sample.png')
I = scipy.misc.imresize(I, (img_height, img_width))
Populating the interactive namespace from numpy and matplotlib
In [4]:

sfm = SfMLearner(batch_size=1,
                 img_height=img_height,
                 img_width=img_width)
sfm.setup_inference_graph(mode=mode)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-85ef1cc8ea5c> in <module>()
      2                  img_height=img_height,
      3                  img_width=img_width)
----> 4 sfm.setup_inference_graph(mode=mode)

/home/timing/Program/SfMLearner/SfMLearner.pyc in setup_inference_graph(self, mode)
     37     def setup_inference_graph(self, mode='depth'):
     38         if mode == 'depth':
---> 39             self.build_depth_test_graph()
     40 
     41     def inference(self, inputs, sess, mode='depth'):

/home/timing/Program/SfMLearner/SfMLearner.pyc in build_depth_test_graph(self)
     18         input_mc = self.preprocess_image(input_uint8)
     19         with tf.name_scope("depth_prediction"):
---> 20             pred_disp, depth_net_endpoints = disp_net(input_mc)
     21             pred_depth = [1./disp for disp in pred_disp]
     22         pred_depth = pred_depth[0]

/home/timing/Program/SfMLearner/nets.pyc in disp_net(tgt_image, is_training)
    104             # There might be dimension mismatch due to uneven down/up-sampling
    105             upcnv7 = resize_like(upcnv7, cnv6b)
--> 106             i7_in  = tf.concat([upcnv7, cnv6b], axis=3)
    107             icnv7  = slim.conv2d(i7_in, 512, [3, 3], stride=1, scope='icnv7')
    108 

TypeError: concat() got an unexpected keyword argument 'axis'

**Comment by tinghuiz** [comment]
Hi, you are probably using an older version of tensorflow. The interface for concat() has changed in tensorflow 1.0.

**Comment by TimingSpace** [comment]
Thank you
