### ISSUE TITLE
How to train on dataset for which we don't have calibration information

### ISSUE THREAD

**Issue by kishankedia** [tinghuiz/SfMLearner#22]
Hi,

I am trying to implement this architecture by passing video dataset taken from youtube. I have been able to create the dataset having three sequence of frames together. I don't have the calibration matrix for this videos, so how best can i train using the following architecture.

How to derive the camera calibration matrix directly knowing the camera properties.

I am thinking of trying to run this architecture by taking video from my mobile but getting blocked in the camera calibration matrix part.

Any help would be greatly appreciated.

**Comment by Yuliang-Zou** [comment]
I don't think you can do this with some random youtube videos. But you can actually get your mobile devices's intrinsics.

**Comment by tinghuiz** [comment]
Like @Yuliang-Zou mentioned, you could try to calibrate your mobile device with existing libraries (e.g. https://www.mathworks.com/help/vision/single-camera-calibration.html) to get the camera intrinsics.

**Comment by kishankedia** [comment]
@Yuliang-Zou  @tinghuiz, I have got the intrinsic parameters for my mobile device. However, after going through the code given in kitti_raw_loader.py , we can see that the p_rect parameter present in the calibration file is used.

P_rect_xx: 3x4 projection matrix after rectification.

P_rect matrix involves both intrinsic and extrinsic parameters. How to derive this matrix for a given camera. I am able to generate the camera matrix (K). Is there any relation or logic that can be used to find this projection matrix using camera calibration matrix?

Can we just use the camera calibration matrix in this network, will it work?

**Comment by Yuliang-Zou** [comment]
No. I think P_rec only contains intrinsics. Check this:

"Here, "unsynced+unrectified" refers to the raw input frames where images are distorted and the frame indices do not correspond, while "synced+rectified" refers to the processed data where images have been rectified and undistorted and where the data frame numbers correspond across all sensor streams. For both settings, files with timestamps are provided. Most people require only the "synced+rectified" version of the files."

http://www.cvlibs.net/datasets/kitti/raw_data.php
