### ISSUE TITLE
About cityscapes datesets

### ISSUE THREAD

**Issue by a610402863** [tinghuiz/SfMLearner#23]
In the link about Cityscapes, I didn't find a data set called leftImg8bit_sequence_trainvaltest.zip. Is it a change of name or other reason?

**Comment by Yuliang-Zou** [comment]
Seems that they changed the way they organize the dataset. I cannot use the preprocessing code for CityScapes either.

**Comment by tinghuiz** [comment]
What kind of error does it give you when you use the preprocessing code?

**Comment by Yuliang-Zou** [comment]
What I did to make the code works:
1) Remove the suffix "_sequence"
2) Swap the orders of "snippet_id" and "tgt_local_frame_id" and orders of "snippet_id" and "curr_local_frame_id" in is_valid_example() and load_image_sequence() in `data/cityscapes/cityscapes_loader.py`

Then I can get 1638 images as training split, 191 images as val split.

**Comment by tinghuiz** [comment]
You need to download the package called `leftImg8bit_sequence_trainvaltest.zip`(324GB) so it contains video snippets. After preprocessing I had ~69K training snippets and ~7K validation snippets.
