### ISSUE TITLE
pose evaluation

### ISSUE THREAD

**Issue by tanwei8699** [tinghuiz/SfMLearner#24]
While evaluating the pose, there differ a lot between the data you provided in pose_eval_data(with the 
directory name "ours results") and the result run by test_kitti_pose.py using the model 100892. 
     Take frame 000860 in sequence 10 for example, the car is turning right. In "ours results",   the tz/tx is 
almost 7,  it's reasonable. But the model 100892 output is not right,  tz/tx is almost 150, meaning there is 
no turning at all. Have you  test the pose estimate performace of the model 100892?

**Comment by royal-feng** [comment]
How to create the test dataset? Use kitti_odom_loader? 
I have no idea, I am new one in SLAM.

**Comment by tanwei8699** [comment]
you can follow this for testing
![crop](https://user-images.githubusercontent.com/13426991/29594758-b9073aa4-87e5-11e7-88e6-af90b30b3994.png)

**Comment by tanwei8699** [comment]
![crop](https://user-images.githubusercontent.com/13426991/29594786-0285c7b8-87e6-11e7-8800-76d635f117c4.png)
@royal-feng You can follow this:

**Comment by tanwei8699** [comment]
you can follow this for testing
![crop](https://user-images.githubusercontent.com/13426991/29594892-b7e2d7ea-87e6-11e7-9c87-4477ab10c481.png)

**Comment by royal-feng** [comment]
@tanwei8699 I see this,I just don't know how to make "/path/to/KITTI/odometry/set/", I don't find any image name in dataset folder to be expressed as  'sequences9/image_2/%s.png'.
How to download the test dataset? 
Thank you for your response

**Comment by tanwei8699** [comment]
@royal-feng You can download "data_odometry_color.zip" from Kitti, http://www.cvlibs.net/download.php?file=data_odometry_color.zip

**Comment by tinghuiz** [comment]
Yeah, the provided model is not exactly the same as the one I used in the paper as there have been some changes to the code that make the original model deprecated. The current model actually performs better than the original one.

**Comment by royal-feng** [comment]
@tinghuiz @tanwei8699 how to connect 5-frame snippets (with the format of `timestamp tx ty tz qx qy qz qw`) into a complete pose estimate? Can I use rgbd_benchmark_tools to finish the work?
