### ISSUE TITLE
pose question

### ISSUE THREAD

**Issue by joyyang1215** [tinghuiz/SfMLearner#25]
Hi,
It's not an error.
I wanna to know why the image_seq's shape is looking like that.
For a 5-sequence case,
(128, 416, 3) => `np.hstack` => (128, 832, 3) => `np.hstack` => ... => (128, 2080, 3)
I thought that it would be (5, 128, 416, 3) for the image_seq!
`pred = sfm.inference(image_seq[None, :, :, :], sess, mode='pose')`
Is there any help?
THANKS

**Comment by tinghuiz** [comment]
These lines (https://github.com/tinghuiz/SfMLearner/blob/master/SfMLearner.py#L283-L285) will unpack the image sequence into a target image (i.e. central frame) and a stack of source images (concatenated along the color channels). The target is further concatenated with the source image stack later for pose network inference (https://github.com/tinghuiz/SfMLearner/blob/master/nets.py#L19).
