### ISSUE TITLE
Will the train code be released?

### ISSUE THREAD

**Issue by daleydeng** [tinghuiz/SfMLearner#3]
Thanks for sharing this excellent work, is it easy to train the model on my custom video dataset?

**Comment by tinghuiz** [comment]
Yes, I am planning to clean up and release the training code after the NIPS deadline. So please check back in early June.

**Comment by daleydeng** [comment]
Thanks for that~~

**Comment by joyousrabbit** [comment]
周老兄，你这个是CVPR oral了，还能投NIPS吗？

**Comment by joyousrabbit** [comment]
@daleydeng Hello, currently you can refer the https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py   they are almost the same.

**Comment by zdx3578** [comment]
wait until  early June.

**Comment by juanilarregui** [comment]
Hi @tinghuiz,

Great work. I'm also looking forward to the training code release.

Cheers!

**Comment by tinghuiz** [comment]
My current estimate of training code release is around June 10. Have been busy with some other matters. Sorry about the delay.

**Comment by tinghuiz** [comment]
Training code has been released.
