### ISSUE TITLE
src to target image projection

### ISSUE THREAD

**Issue by AmirmasoudGhasemi** [tinghuiz/SfMLearner#31]
Hi,
I am trying to expand your project for my thesis and I figure out that there might be a logical error in your implementation and even in the paper itself (figure 3 and section 3.1).
As I understood, you are extracting depth information from target image due to:
https://github.com/tinghuiz/SfMLearner/blob/febf0d375ea28fed15aa3ba6614d704a6690b464/SfMLearner.py#L30-L31
and then pass this depth along with curr_src_image_stack into the projective_inverse_warp function to calculate curr_proj_image https://github.com/tinghuiz/SfMLearner/blob/febf0d375ea28fed15aa3ba6614d704a6690b464/SfMLearner.py#L68-L72.
https://github.com/tinghuiz/SfMLearner/blob/febf0d375ea28fed15aa3ba6614d704a6690b464/SfMLearner.py#L73 and also equation1 in original paper show that you are trying to build the target image based on pixel coordinates of src images https://github.com/tinghuiz/SfMLearner/blob/febf0d375ea28fed15aa3ba6614d704a6690b464/utils.py#L97
If it is true, you need to feed depth information of "src image" not "target image" into the projective_inverse_warp function, or you can use target image and its depth to build src image(figure 3 in the paper shows that the target images pixels will be projected into the src view but section 3.1 and equation1 contradict this subject).

**Comment by tinghuiz** [comment]
Hi, you might have misunderstood how inverse warping works. Here we are not splatting (aka forward warping) the target pixels onto the source frame, which is undesirable as splatting would lead to holes in the synthesized image. Instead, we do inverse warping, i.e. for each target pixel we first compute where it would land in the source image by perspective projection (using camera intrinsics, inferred depth and pose), and then bilinearly sample among the neighbors of the projected coordinate in the source image. The warped/sampled value is then used to compute the loss w.r.t. the ground-truth target pixel value.
