### ISSUE TITLE
How can I generate 5-frame snippet from full trajectory data?

### ISSUE THREAD

**Issue by deruci** [tinghuiz/SfMLearner#35]
Hello,

Can you share the exact way to get 5-frame snippet data from full trajectory to evaluate the method? (quarternion computation and/or quaternion to rotation matrix ..)

**Comment by ClementPinard** [comment]
you can get the data for KITTI here, images and ground truth : 
http://www.cvlibs.net/datasets/kitti/eval_odometry.php
Once you get it, you must run the [data code](https://github.com/tinghuiz/SfMLearner/blob/master/data/prepare_train_data.py), with option 'kitti_odom'

Finally, you can follow instructions at the end of the README.md :

`python test_kitti_pose.py --test_seq [sequence_id] --dataset_dir /path/to/KITTI/odometry/set/ --output_dir /path/to/output/directory/ --ckpt_file /path/to/pre-trained/model/file/`

to generate predictions and then

`python kitti_eval/eval_pose.py --gtruth_dir=/directory/of/groundtruth/trajectory/files/ --pred_dir=/path/to/output/directory/
`
to evaluate them

If you wonder where quaternion to matrix is done, it's [here](https://github.com/tinghuiz/SfMLearner/blob/master/kitti_eval/pose_evaluation_utils.py)

**Comment by deruci** [comment]
Thank you for your kind response.

What I was curious about is actually how to generate pose snippets from full trajectory.
As you mentioned in README.md, I downloaded pose evaluation data from following script ;
 ./kitti_eval/download_kitti_pose_eval_data.sh

After that, some ground poses are downloaded like
09_full.txt, 10_full.txt, and corresponding snippet data from 000000.txt to 001586.txt (for 09)

I wonder how to generate those files to evaluate this method for entire KITTI and/or other odometry data.

**Comment by ClementPinard** [comment]
you generate the pose predictions with the code `test_kitti_pose.py`
you evaluate them with `kitti_eval/eval_pose.py`

Downloading the predictions is just bypassing the first code (`test_kitti_pose.py`), but you can run it with your own trained network.

**Comment by hemangchawla** [comment]
How do you do the same for the output of ORB-SLAM? Since ORB-SLAM only outputs the Keyframes, how is the snippet selected and associated?
