### ISSUE TITLE
1.problem about the process of generating IMG frames    2.some errors during the training data

### ISSUE THREAD

**Issue by hzb321** [tinghuiz/SfMLearner#36]
1. when  executing ` python data/prepare_train_data.py --dataset_dir=/path/to/cityscapes/dataset/ --dataset_name='cityscapes' --dump_root=/path/to/resulting/formatted/data/ --seq_length=3 --img_width=416 --img_height=171 --num_threads=4` The result is 5 frames,such as:
![5frames](http://img.blog.csdn.net/20171125092359156?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvaHpiMzIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast),while executing on other pc(gpu:1080ti),it's 3 frames:
![3frames](http://img.blog.csdn.net/20171125092608429?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvaHpiMzIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

2.Follow the steps from [python train.py --dataset_dir=/path/to/the/formatted/data/ --checkpoint_dir=/where/to/store/checkpoints/ --img_width=416 --img_height=128 --batch_size=4](https://github.com/tinghuiz/SfMLearner)the result is :
![result](http://img.blog.csdn.net/20171125093043467?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvaHpiMzIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
so i would to know how to solve this problems ?  looking forward to your reply ,thank you very much !

**Comment by hzb321** [comment]
1. when  executing ` python data/prepare_train_data.py --dataset_dir=/path/to/cityscapes/dataset/ --dataset_name='cityscapes' --dump_root=/path/to/resulting/formatted/data/ --seq_length=3 --img_width=416 --img_height=171 --num_threads=4` The result is 5 frames,such as:
![5frames](http://img.blog.csdn.net/20171125092359156?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvaHpiMzIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast),while executing on other pc(gpu:1080ti),it's 3 frames:
![3frames](http://img.blog.csdn.net/20171125092608429?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvaHpiMzIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

2.Follow the steps from [python train.py --dataset_dir=/path/to/the/formatted/data/ --checkpoint_dir=/where/to/store/checkpoints/ --img_width=416 --img_height=128 --batch_size=4](https://github.com/tinghuiz/SfMLearner)the result is :
![result](http://img.blog.csdn.net/20171125093043467?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvaHpiMzIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
so i would to know how to solve this problems ?  looking forward to your reply ,thank you very much !

**Comment by tinghuiz** [comment]
1) Do you mean you get different results on different machines when running the same data preparation command?

2) Can you check if your training images can be properly read/displayed by standard libraries like scipy or pillow?

**Comment by warmkid** [comment]
how do you download leftImg8bit_sequence_trainvaltest.zip from Cityscapes?  that notes it needs request, what does it mean?

**Comment by tinghuiz** [comment]
You need to email the Cityscapes organizers to request a download link.

**Comment by hzb321** [comment]
Sorry, too late to see your reply .I applyed  for the link from the Cityscapes organizers in your way.

**Comment by JoeFang123** [comment]
I wonder whether you have received the link from Cityscapes organizers. I applied for the link in the last Wednesday but didn't get any response.
