### ISSUE TITLE
Question about pose estimation network

### ISSUE THREAD

**Issue by marcel1991** [tinghuiz/SfMLearner#38]
I am wondering how you can use so many downsampling convolutions in your pose network though the input image is 128 pixels in height. The resulting feature map would have a height below 0 with all the convolutions or am I wrong? Are you using zero padding or something for the convolutions? It's not clear for me to see.

**Comment by tinghuiz** [comment]
There are 7 stride=2 convolutions for the pose network, which would make the height of the last feature map equal to 1 if the input image is 128 pixels.
