### ISSUE TITLE
Can you share the code how did you get static_frames.txt?

### ISSUE THREAD

**Issue by Youngkl0726** [tinghuiz/SfMLearner#40]
Can you share the code how did you get static_frames.txt?
Thanks.

**Comment by tinghuiz** [comment]
I used a standard optical flow library: https://people.csail.mit.edu/celiu/OpticalFlow/, and then get the static frames by thresholding on the magnitude of the predicted flows.

**Comment by abeyang00** [comment]
@tinghuiz do you remember the value for threshold? trying to create statc_frame.txt with my own data

Thank you in advance

**Comment by lxcr007** [comment]
@abeyang00 Do you get static_ frames.txt ? Can you share the code? 
Thank you very much.
