### ISSUE TITLE
The way to save the disparity into image

### ISSUE THREAD

**Issue by keishatsai** [tinghuiz/SfMLearner#44]
Hi,
I follow the demo code and try to save the depth image by using test_kitti_depth.py
Images I saved are not what I expected.......
The original input image:
![0000000069](https://user-images.githubusercontent.com/8175070/34512571-57ef30ec-f09e-11e7-9622-a3e07a570928.jpg)
The predicted depth:
![keisha_disp](https://user-images.githubusercontent.com/8175070/34512521-00006054-f09e-11e7-8e05-0e1e735d8cda.png)
The resized predicted depth:
![keisha_disp_resize](https://user-images.githubusercontent.com/8175070/34512524-00f5ab40-f09e-11e7-87ed-d9e682761dff.png)

those predictions I saved don't look like a proper depth map. Is there anything that I misunderstood?
Here is my code:

>  
pred = sfm.inference(inputs, sess, mode='depth')
pred_disp = normalize_depth_for_display(pred['depth'][0,:,:,0])
cv2.imwrite('data/kitti/raw_disp.png', pred_disp)
fh_disp = open('data/kitti/raw_disp.png', 'r')
raw_disp = pil.open(fh_disp)
img_disp = raw_disp.resize((1242, 375), pil.ANTIALIAS)
img_disp.save('data/kitti/disp_resize.png')          
> 

Thanks

**Comment by keishatsai** [comment]
I found that I should use matplotlib to save my instead of using opencv.
Now it is correct.

**Comment by mrwtakev** [comment]
@keishatsai 
Hello,
I also have this problem,and I use plt.savefig() instead of using imwrite(),but I found plt.savefig() save image same as using imshow().Actually,I want get depth map and use it in other program and I want to know how to do it,can you give me some suggests?
Thank you.
