### ISSUE TITLE
How to interpolate ground-truth from sparse measurements?  (about figure6 in the paper)

### ISSUE THREAD

**Issue by keishatsai** [tinghuiz/SfMLearner#45]
Hi, 

I am wondering that how to interpolate ground-truth from sparse measurements as it says in the paper.
There is no explanation for that.
Could anyone teach me how? Thank you :)

**Comment by joschuck** [comment]
This is a quick solution. Just apply a max convolution. In this example I read a grayscale .png file, convert it to a numpy array, then apply the max convolution.
[See this gist for smoothing lidar images](
https://gist.github.com/joschuck/19b26aab50e6f302602de6c32488069b)
I hope I understood your question.

**Comment by keishatsai** [comment]
@joschuck 
Thanks for the help. This is exactly what I am looking for. Let's me try the method first.

**Comment by keishatsai** [comment]
Hi @joschuck,
I just found out there is another problem. Have you tried to reproject the 3D velodyne points to the colour image because I just realised that there is no groundtruth in some KITTI dataset, i.e. 2011_09_26/2011_09_26_0009_sync/

What would you suggest me to do? Just reproject the velodyne points?
Thanks.

**Comment by joschuck** [comment]
Yes I've had this problem too. For some images there is the ground truth missing and the other way around. I just ignore those. I.e. change the following line 96 (commit 7b98ef2b16dc0fe9d0514d6975c19b739c65c920) in kitti_eval/depth_evaluation_utils.py to

    if os.path.isfile(data_root + im) and os.path.isfile(data_root + vel):

**Comment by keishatsai** [comment]
Hi @joschuck, I was trying your code, but errors come in.
It seems that I have to form the imagefirst from the velodyne bin file, and I right?

**Comment by keishatsai** [comment]
Hi @joschuck,
I got error message when running your demo code. Could you help me to clarify the problem?
Thanks
------
Traceback (most recent call last):
  File "projectVelo_detail.py", line 238, in <module>
    smooth_lidar_image = getVELOIMG.fromarray(ndimage.filters.maximum_filter(lidar_image, (5,5)), mode='I')
  File "/usr/lib/python2.7/dist-packages/scipy/ndimage/filters.py", line 970, in maximum_filter
    cval, origin, 0)
  File "/usr/lib/python2.7/dist-packages/scipy/ndimage/filters.py", line 903, in _min_or_max_filter
    sizes = _ni_support._normalize_sequence(size, input.ndim)
  File "/usr/lib/python2.7/dist-packages/scipy/ndimage/_ni_support.py", line 64, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank

**Comment by tinghuiz** [comment]
For interpolation I just use the depth value from the nearest pixel with a valid measurement.
