### ISSUE TITLE
Question about seq_length

### ISSUE THREAD

**Issue by jookty** [tinghuiz/SfMLearner#47]
I am trying to train and test the SfMLeaner model. 
But I found that seq_length's values in two files(train.py and test_kitti_pose.py) are different. 
seq_length is 3 in train.py and 5 in test_kitti_pose.py

I set the value of seq_length  to same number(3 or 5) and trained and tested, but error was raised.

How to fix it?

**Comment by tinghuiz** [comment]
As mentioned in the paper, for the depth experiments we used the model trained with seq_length=3, and for the pose experiments we used the model trained with seq_length=5.
