### ISSUE TITLE
question about cityscapes dataset preparation

### ISSUE THREAD

**Issue by amiltonwong** [tinghuiz/SfMLearner#5]
Hi, @tinghuiz ,

I'm trying to prepare cityscapes dataset. According to the [download page](https://www.cityscapes-dataset.com/downloads/) , generally we'll download "leftImg8bit_trainvaltest.zip" which are not consecutive frames and used for segmentation tasks. I guess we should download a dataset with consecutive frames, could you reply the name of exact dataset zip file to prepare? e.g. leftImg8bit_trainextra.zip / leftImg8bit_demoVideo.zip / leftImg8bit_sequence_trainvaltest.zip / etc  (which one ?)

Thanks!

**Comment by tinghuiz** [comment]
Just updated the readme. Please take a look and let me know if you have further questions.
