### ISSUE TITLE
White blank depth on my data

### ISSUE THREAD

**Issue by athus1990** [tinghuiz/SfMLearner#53]
Hi,
Thanks a lot for the amazing work and well written code. I created my own driving dataset similar to Kitti and arranged in the same way as ur prepared kitti folder and trained from scratch(matching the same image dimensions and scaling the intrinsic matrix accordingly). It seem to be training well and the pose estimation seems to be okay as the projection errors are looking good).However my disparity are all white. But the same code works on KITTI.
 (ie) they are very small values while training and they never converge.

More specifically check these out:

![image](https://user-images.githubusercontent.com/7275643/36568907-949aab0c-17e0-11e8-985c-4aff49b1e734.png)

![image](https://user-images.githubusercontent.com/7275643/36568989-d3b9fa5e-17e0-11e8-85f3-5a9c714766fe.png)

![image](https://user-images.githubusercontent.com/7275643/36569034-fb501a08-17e0-11e8-9e1a-f5d4e83ebe88.png)

![image](https://user-images.githubusercontent.com/7275643/36569106-513199ec-17e1-11e8-9b72-ab849222ee15.png)

Clearly the depth values are all close to zero still. Even though the network seems to be reducing the total loss and training well. One thing I also noticed is that my disparity values are not smoothly distributed while training like yours in KITTI:
![image](https://user-images.githubusercontent.com/7275643/36569249-e122cc7e-17e1-11e8-980b-a528cd3d4478.png)

Could you please tell me what parameters I can change to help the network train. I dont understand why it doesn't train on a similar dataset. Only Ground truth is camera intrinsics. If my intrinsics is wrong then my projection errors will also be wrong right? Pls help me find out what I am doing wrong. Thanks a lot for ur help.

**Comment by tinghuiz** [comment]
The 'smooth_weight' might be too high. Can you try reducing it and see what happens?

**Comment by hondaathma** [comment]
Hi @tinghuiz ,Thanks a lot for your reply. Tried setting values from 0.05 to 0.5 as my smoothness weight. still no use.

![image](https://user-images.githubusercontent.com/26149657/36621764-9f9108ca-18ae-11e8-8e03-21a916c2c954.png)

I cant understand what I am doing wrong. I scaled my intrinsics to the same size you used(416,218). I sampled 3 consecutive frames from my dashcam video (at 30hz).I am guessing my camera instrinsic params are correct as inverse projection seems okay. Could you suggest anything else I can try. My depth distribution is similar to the scale0_depth you see above.

**Comment by tinghuiz** [comment]
There might be too little camera motion between consecutive frames in your video. You can try subsample (e.g. every 3 frames) your video to match the KITTI frame rate (~12hz).

**Comment by hondaathma** [comment]
you mean have a 12Hz frame rate between the source and the target? or have a 12hz frame rate between each batch(ie between each source,target,source triplet).

**Comment by tinghuiz** [comment]
Between the source and the target.

**Comment by hondaathma** [comment]
Sure thing! I will try that and update! Thanks!

**Comment by tinghuiz** [comment]
Since there has not been an update for a while, I'll close this issue for now.
