### ISSUE TITLE
Failed to evaluate depth using given predictions (velo2cam)

### ISSUE THREAD

**Issue by kristijanbartol** [tinghuiz/SfMLearner#55]
Hi,

I followed instructions from readme.md. First I download KITTI dataset using official [script](http://www.cvlibs.net/download.php?file=raw_data_downloader.zip) and then ran bash script from downloading predictions:

```
bash ./kitti_eval/download_kitti_depth_predictions.sh
```

Then I try to evaluate these predictions:

```
python kitti_eval/eval_depth.py --kitti_dir=/path/to/raw/kitti/dataset/ --pred_file=kitti_eval/kitti_eigen_depth_predictions.npy
```

but I get the following error:

```
Traceback (most recent call last):
  File "kitti_eval/eval_depth.py", line 77, in <module>
    main()
  File "kitti_eval/eval_depth.py", line 37, in main
    True)
  File "/home/kristijan/depth/sfm/SfMLearner/kitti_eval/depth_evaluation_utils.py", line 175, in generate_depth_map
    velo2cam = np.hstack((velo2cam['R'].reshape(3,3), velo2cam['T'][..., np.newaxis]))
ValueError: cannot reshape array of size 1 into shape (3,3)
```

I tried checking what could be wrong with velo2cam variable, i.e. which part of instructions did I miss, but I can't see where I made mistake here.

I'm trying to run it on Ubuntu 16.04 LTS without available GPU on the computer.

P.S. I tried running pose evaluation and it ran fine.

**Comment by kristijanbartol** [comment]
Fixed it. I changed

```
data[key] = np.array(map(float, value.split(' ')))
```

to

```
data[key] = np.array([float(v) for v in value.split(' ')])
```

Then I ran into another error

```
Traceback (most recent call last):
  File "kitti_eval/eval_depth.py", line 77, in <module>
    main()
  File "kitti_eval/eval_depth.py", line 37, in main
    True)
  File "/home/kristijan/depth/sfm/SfMLearner/kitti_eval/depth_evaluation_utils.py", line 211, in generate_depth_map
    dupe_inds = [item for item, count in Counter(inds).iteritems() if count > 1]
AttributeError: 'Counter' object has no attribute 'iteritems'
```

because [Python removed iteritems()](https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems-when-trying-to-use-networkx), so I just called items() method instead.

**Comment by ahmetkorkmaz82** [comment]
you saved me thank you
