### ISSUE TITLE
How to train pose_net?

### ISSUE THREAD

**Issue by royal-feng** [tinghuiz/SfMLearner#56]
I changed the input of pose_net to 2-frame snippets images for the purpose that I want to estimate the the pose between target-frame image and its next frame image. But the result turn to be strange, like that:
Epoch: [ 1] [    1/ 4590] time: 5.4610/it loss: 1.265
[[ 5.5594608e-02  4.1611232e-02 -2.9045379e+00 -2.4940830e-04
   7.8899926e-04  1.1408931e-03]]
Epoch: [ 1] [    2/ 4590] time: 0.6910/it loss: 1.345
[[ 5.4365378e-02  4.0248752e-02 -2.8675201e+00  4.0297356e-04
   5.0060626e-05  4.3766299e-04]]
Epoch: [ 1] [    3/ 4590] time: 0.7220/it loss: 0.920
[[ 5.3226665e-02  3.9065529e-02 -2.8294766e+00  1.0433119e-03
  -6.4546510e-04 -2.9349671e-04]]
Epoch: [ 1] [    4/ 4590] time: 0.7360/it loss: 0.700
[[ 5.3099021e-02  3.8820472e-02 -2.8395672e+00  1.3501836e-03
  -1.1050075e-03 -1.0100374e-03]]
Epoch: [ 1] [    5/ 4590] time: 0.7090/it loss: 0.605
[[ 5.3082950e-02  3.8819354e-02 -2.8512640e+00  1.3580802e-03
  -1.4360860e-03 -1.3620675e-03]]
Epoch: [ 1] [    6/ 4590] time: 0.7270/it loss: 0.694
[[ 5.3565979e-02  3.9367087e-02 -2.8749318e+00  1.0619831e-03
  -1.4116894e-03 -1.2049747e-03]]
Epoch: [ 1] [    7/ 4590] time: 0.7130/it loss: 1.242
[[ 5.3712413e-02  3.9615326e-02 -2.8820136e+00  8.1495516e-04
  -1.3181081e-03 -1.1293018e-03]]
Epoch: [ 1] [    8/ 4590] time: 0.7580/it loss: 1.189
[[ 5.3978346e-02  3.9846379e-02 -2.8900311e+00  6.0747087e-04
  -1.1298185e-03 -1.1336819e-03]]
Epoch: [ 1] [    9/ 4590] time: 0.7700/it loss: 0.841
[[ 5.4268718e-02  4.0138055e-02 -2.9024613e+00  3.9428068e-04
  -1.0965415e-03 -1.1796508e-03]]
Epoch: [ 1] [   10/ 4590] time: 0.7210/it loss: 0.654
[[ 5.4592371e-02  4.0351395e-02 -2.9127421e+00  2.6452739e-04
  -9.6347183e-04 -1.3487849e-03]]
Do you think this 6-dof pose is right?Then I test the pose_net，its result to be the same pose between different images,like that:
Progress: 1/4071
[[ 5.5594608e-02  4.1611228e-02 -2.9045382e+00 -2.4940830e-04
   7.8899920e-04  1.1408930e-03]]
Progress: 2/4071
[[ 5.5594608e-02  4.1611228e-02 -2.9045382e+00 -2.4940830e-04
   7.8899920e-04  1.1408930e-03]]
Progress: 3/4071
[[ 5.5594608e-02  4.1611228e-02 -2.9045382e+00 -2.4940830e-04
   7.8899920e-04  1.1408930e-03]]
Progress: 4/4071
[[ 5.5594608e-02  4.1611228e-02 -2.9045382e+00 -2.4940830e-04
   7.8899920e-04  1.1408930e-03]]
Progress: 5/4071
[[ 5.5594608e-02  4.1611228e-02 -2.9045382e+00 -2.4940830e-04
   7.8899920e-04  1.1408930e-03]]
Progress: 6/4071
[[ 5.5594608e-02  4.1611228e-02 -2.9045382e+00 -2.4940830e-04
   7.8899920e-04  1.1408930e-03]]
Progress: 7/4071
[[ 5.5594608e-02  4.1611228e-02 -2.9045382e+00 -2.4940830e-04
   7.8899920e-04  1.1408930e-03]]
I check out the input, the inputs is correct, they are different image, but the result is same. Do you have some idea for this problem?

**Comment by tinghuiz** [comment]
Does the depth map look reasonable?
