### ISSUE TITLE
the result i think have some puzzle

### ISSUE THREAD

**Issue by warmkid** [tinghuiz/SfMLearner#58]
the 09 sequences on KITTI should be like the picture 1(according to the **09_full.txt**), but when i plot your pose,get the picture 2, and i found the **gruondtruth file you offer**(divided every 5 frames) is picture 3, can you tell me how to plot the trajectory according to the pose files.

![truth](https://user-images.githubusercontent.com/17879844/37017889-40e26e16-214d-11e8-99bd-813814da5e40.PNG)
![tinghui](https://user-images.githubusercontent.com/17879844/37017905-4e4fb96e-214d-11e8-95e4-cf785eb78019.PNG)
![truth_offer](https://user-images.githubusercontent.com/17879844/37017906-4e7f0a8e-214d-11e8-9e52-dd7b661a7365.PNG)

**Comment by tinghuiz** [comment]
You should transform each sequence trajectory into a global coordinate frame (i.e. the first frame of the sequence).
