### ISSUE TITLE
question about kitti dataset preparation

### ISSUE THREAD

**Issue by amiltonwong** [tinghuiz/SfMLearner#6]
Hi, @tinghuiz ,

I also hope to have a clarification on kitti dataset preparation. 
First , according to the kitti raw [download page](http://www.cvlibs.net/datasets/kitti/raw_data.php) , there are up to 100 sequences (e.g. 2011_09_26_drive_0001, 2011_09_26_drive_0002, ...) . Could you clarify which sequences should we download for preparation?

Thanks!

**Comment by tinghuiz** [comment]
Just updated the readme. Please take a look and let me know if you have further questions.

**Comment by amiltonwong** [comment]
Hi, @tinghuiz ,

After download and unzip the raw dataset, I run the `prepare_train_data.py` and got the following error:

```
(tf1.0_gpu) root@milton-OptiPlex-9010:/data/code3/SfMLearner# python data/prepare_train_data.py --dataset_dir=/data/kitti_raw/ --dataset_name='kitti_raw_eigen' --dump_root=/data/kitti_raw_formatted/ --seq_length=3 --img_width=416 --img_height=128 --num_threads=4
Traceback (most recent call last):
  File "data/prepare_train_data.py", line 106, in <module>
    main()
  File "data/prepare_train_data.py", line 71, in main
    seq_length=args.seq_length)
  File "/data/code3/SfMLearner/data/kitti/kitti_raw_loader.py", line 28, in __init__
    self.collect_train_frames()
  File "/data/code3/SfMLearner/data/kitti/kitti_raw_loader.py", line 45, in collect_train_frames
    drive_set = os.listdir(self.dataset_dir + date + '/')
FileNotFoundError: [Errno 2] No such file or directory: '/data/kitti_raw/2011_09_26/'
```

As the default directory structure for kitti_raw  is :

2011_09_26_drive_0001/
---------------------------2011_09_26_drive_0001_sync/
------------------------------------------------------------image_00/
-----------------------------------------------------------------------data/
-----------------------------------------------------------------------timestamps.txt
-----------------------------------------------------------------------------0000000000.png                             
---------------------------calib_cam_to_cam.txt
---------------------------calib_imu_to_velo.txt
---------------------------calib_velo_to_cam.txt
---------------------------tracklet_labels.xml

Would you help to fix this issue in `kitti_raw_loader.py`?

Thanks~

**Comment by tinghuiz** [comment]
Did you use `raw_data_downloader.sh` provided on the KITTI website to download the data? If so, you should get a directory structure like `2011_09_26/2011_09_26_drive_0001_sync/`, which is what the code assumes.
