### ISSUE TITLE
Problem regarding Testing Code.

### ISSUE THREAD

**Issue by maheshworkp1** [tinghuiz/SfMLearner#62]
I'm getting the following error when trying to run the Depth Testing code on the raw kitti dataset. I have provided the .index file as the input to the --ckpt_file parameter.

"NotFoundError (see above for traceback): Tensor name "depth_net/cnv4/biases" not found in checkpoint files /home/maheshp1/SfMLearner/checkP/model-191178.index"

When I gave .meta file as -ckpt_file parameter, I'm getting the following error:
"DataLossError (see above for traceback): Unable to open table file /home/maheshp1/SfMLearner/checkP/model-191178.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_12 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_12/tensor_names, save/RestoreV2_12/shape_and_slices)]]
"
I am getting the same error even when I have provided the checkpoint file directly.

Can someone explain the problem and how I can resolve it?

**Comment by B-Betty** [comment]
your path of  -ckpt_file is 'xxx/model-191178'

**Comment by maheshworkp1** [comment]
Thanks for the help. I was able to run the model.
Also, can I run the pose network testing code test_kitti_pose.py on raw KITTI dataset instead of the odometry dataset?

**Comment by B-Betty** [comment]
recently, i also want to how to run the pose network testing code test_kitti_pose.py on raw KITTI dataset instead of the odometry dataset

**Comment by tinghuiz** [comment]
I haven't tried it myself, but I think as long as you format the data in the same manner it should work similarly.

**Comment by ShahZebYousafzai** [comment]
> Thanks for the help. I was able to run the model.
> Also, can I run the pose network testing code test_kitti_pose.py on raw KITTI dataset instead of the odometry dataset?
I am still having issue running the code. I am giving the command line like below
"python test_kitti_depth.py --dataset_dir ./kitti_raw_data/ --output_dir ./output/ --ckpt_file ./checkpoints/model.latest.data-00000-of-00001"
After running this, I get this:
"DataLossError (see above for traceback): Unable to open table file ./checkpoints/model.latest.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at test_kitti_depth.py:31)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[{{node save/RestoreV2/_71}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_75_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]"

**Comment by ShahZebYousafzai** [comment]
> your path of -ckpt_file is 'xxx/model-191178'

I am giving the following command line:

"python test_kitti_depth.py --dataset_dir ./dataset/kitti_raw_data/ --output_dir ./output/ --ckpt_file ./models/model-190532.data-00000-of-00001"

But still I am getting the DataLossError
