### ISSUE TITLE
Testing image size issues

### ISSUE THREAD

**Issue by shubhamwagh** [tinghuiz/SfMLearner#63]
I wanted to test this network on an image of size (680 - height, 414 - width) using the pre-trained model.
It gives the following error -

ValueError: Dimension 1 in both shapes must be equal, but are 86 and 85. Shapes are [1,86,52] and [1,85,52]. for 'depth_prediction/depth_net/concat_3' (op: 'ConcatV2') with input shapes: [1,86,52,128], [1,85,52,128], [] and with computed input tensors: input[2] = <3>.

Also, in paper it is mentioned that the both the depth and pose networks can be run fully-convolutionally for images of arbitrary size at test time.

**Comment by tinghuiz** [comment]
You can add another 'resize_like()' layer before the layer that gives you size mismatch error.

**Comment by mehbas92** [comment]
Hi @tinghuiz @shubhamwagh 
Could you tell me where exactly to make this change? Is it in SfMLearner.py?
