### ISSUE TITLE
question about training.

### ISSUE THREAD

**Issue by hjf579068** [tinghuiz/SfMLearner#64]
hello
    tinghuiz, I want to train the depth model using the dataset captured by myself, and I have two questions.
   First, when I collect images, what should I take care of？Is there any request to the dataset when training the depth model.
   Sencond, can you tell me your PC‘s hardware environment? And i use the GPU version's tensorflow,and it run slowly, is there any secrect to improve the training speed?
    I wait you answer , thank you!!!

**Comment by tinghuiz** [comment]
You should definitely calibrate your camera and get the intrinsics. Also try to move the camera in a reasonable speed or sub-sample the frames so that there's enough camera motion within a training sequence.

I used a Titan Xp GPU for the experiments, and it took 4-6 hours for training on KITTI.
