### ISSUE TITLE
Unknown command line flag 'num_source'

### ISSUE THREAD

**Issue by xiongdemao** [tinghuiz/SfMLearner#69]
python train.py --dataset_dir=datafile/resulting/ --checkpoint_dir=SfMLearner/checkpoints/ --img_width=416 --img_height=128 --batch_size=4
/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/colors.py:680: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  not cbook.is_string_like(colors[0]):
{'batch_size': <absl.flags._flag.Flag object at 0x7f65f4e99cd0>,
 'beta1': <absl.flags._flag.Flag object at 0x7f65f4e99b50>,
 'checkpoint_dir': <absl.flags._flag.Flag object at 0x7f65f6daa050>,
 'continue_train': <absl.flags._flag.BooleanFlag object at 0x7f65f4bdb050>,
 'dataset_dir': <absl.flags._flag.Flag object at 0x7f65fb258510>,
 'explain_reg_weight': <absl.flags._flag.Flag object at 0x7f65f4e99c50>,
 'h': <tensorflow.python.platform.app._HelpFlag object at 0x7f65f4bdb090>,
 'help': <tensorflow.python.platform.app._HelpFlag object at 0x7f65f4bdb090>,
 'helpfull': <tensorflow.python.platform.app._HelpfullFlag object at 0x7f65f4bdb110>,
 'helpshort': <tensorflow.python.platform.app._HelpshortFlag object at 0x7f65f4bdb150>,
 'img_height': <absl.flags._flag.Flag object at 0x7f65f4e99d50>,
 'img_width': <absl.flags._flag.Flag object at 0x7f65f4e99dd0>,
 'init_checkpoint_file': <absl.flags._flag.Flag object at 0x7f65f4e99a10>,
 'learning_rate': <absl.flags._flag.Flag object at 0x7f65f4e99ad0>,
 'max_steps': <absl.flags._flag.Flag object at 0x7f65f4e99ed0>,
 'save_latest_freq': <absl.flags._flag.Flag object at 0x7f65f4e99fd0>,
 'seq_length': <absl.flags._flag.Flag object at 0x7f65f4e99e50>,
 'smooth_weight': <absl.flags._flag.Flag object at 0x7f65f4e99bd0>,
 'summary_freq': <absl.flags._flag.Flag object at 0x7f65f4e99f50>}
Traceback (most recent call last):
  File "/home/pytest/SfMLearner/train.py", line 44, in <module>
    tf.app.run()
  File "/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/pytest/SfMLearner/train.py", line 41, in main
    sfm.train(FLAGS)
  File "/home/pytest/SfMLearner/SfMLearner.py", line 204, in train
    opt.num_source = opt.seq_length - 1
  File "/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 496, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 374, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'num_source'

**Comment by kristijanbartol** [comment]
PR created: https://github.com/tinghuiz/SfMLearner/pull/70

**Comment by xiongdemao** [comment]
thank you very mach！！！
