### ISSUE TITLE
How to evaluate?

### ISSUE THREAD

**Issue by thuyang** [tinghuiz/SfMLearner#7]
Hi @tinghuiz,

Thank you for sharing with us the training code. How should I evaluate based on the output? I observed that the depth output is resized to [0,1]. How can I restore the absolute depth value for evaluation?

Thank you

**Comment by tinghuiz** [comment]
Hi, as mentioned in the paper, "Since the depth predicted by our method is de-
fined up to a scale factor, for evaluation we multiply the predicted
depth maps by a scalar s that matches the median with the groundtruth,
i.e. s = median(D_gt)/median(D_pred)".

**Comment by thuyang** [comment]
Thank you Tinghui. I tried implementing a depth evaluation following this repository: https://github.com/mrharicot/monodepth/blob/master/utils/evaluate_kitti.py. But I cannot replicate the numbers in you paper. I assumed there must be details between you evaluation with this one? Do you have plan to release the evaluation tools?

Thank you again.

**Comment by tinghuiz** [comment]
Hm, what numbers are you getting? I do plan to release the evaluation code sometime, which is mostly based on clement's code. I can send the current version to you if you send me an email.

**Comment by thuyang** [comment]
Great! Email sent. Thank you!

**Comment by thuyang** [comment]
Hi Tinghui, I haven't received your email. Just in case that my email to you is spammed. My email address is zhenheny@usc.edu. Thank you!

**Comment by JackHenry1992** [comment]
Hi Tinghui, I've sent you a email for requesting evaluate code, could you give me this code ? My email address is 1005715562@qq.com, Thank you!

**Comment by tinghuiz** [comment]
Hi guys, I just updated the repo with the depth evaluation code. Let me know if you have any questions.

**Comment by tothniki** [comment]
Hi,
Can somebody (@tinghuiz or others) explain me the theory behind of this scale factor? 
So how does somebody came up with the idea of this scale up factor and method? How did you figure out this median computation and how do you know that this method is good for scaling? Thanks!
