### ISSUE TITLE
Pose network - expected sequence frame rate in the training dataset

### ISSUE THREAD

**Issue by wmuron** [tinghuiz/SfMLearner#72]
Thanks for releasing the paper and the code for your work.

I am trying to train the network on my own dataset. Based on the dumped estimated pose records I suspect that the sample rate for the input sequences is about 10 fps. Given the fact that I only have access to 15fps videos and you mentioned that the frames should _contain_ enough motion between them, I tried to sample every second frame, which gives me 7.5 fps sequences. 

I searched through the training code, but I couldn't see anything that would use the prior knowledge of the sequence timing. Does the network require the specific input fps, or can it adapt to run on arbitrary values? If so, do you think that network can generalize well to estimate the motion in sequences with different frame rates than used in training?

Thanks

**Comment by tinghuiz** [comment]
The code doesn't build in any prior knowledge of the sequence timing. But intuitively, if the camera motion is too small (e.g. static image sequence) or too large (e.g. no scene overlap between consecutive frames),  there's no way the network could learn meaningful depth or pose from the data.
