### ISSUE TITLE
How to generate 5 - frame snippets from ground truth

### ISSUE THREAD

**Issue by ma8sa** [tinghuiz/SfMLearner#73]
I wanted to test the SFMLearner on other kitti sequences apart from the 9,10.
 How do I generate 5 frame snippets from the KITTI poses.txt

**Comment by yzcjtr** [comment]
You can refer to this script I wrote: 
https://github.com/yzcjtr/GeoNet/blob/master/kitti_eval/generate_pose_snippets.py
