### ISSUE TITLE
how to predict pose with my data?

### ISSUE THREAD

**Issue by goeatsmall** [tinghuiz/SfMLearner#83]
I want to predict depth and pose with my video
I already convert video to images and get depth successfully (by using "demo.ipynb")
but I don't know how to predict pose from my data
( I am just a beginner )

**Comment by kristijanbartol** [comment]
You need three things: 
- **camera intrinsics** (find a way to obtain it from your camera)
- **depth estimation** for target image
- **pose estimation** for each of the source images with respect to target image.

To jointly estimate depth and pose, you need to get sequence of images from your video and then feed them into a static computational graph. The only way I say is to feed a sequence and then iterate through source images inside a graph. Then you can evaluate estimated depth and pose.

Note that intrinsics can be read only once and put in a graph as a constant.

**Comment by goeatsmall** [comment]
@kristijanbartol Thanks for your reply.
I get the depth with  `pred = sfm.inference(I[None,:,:,:], sess, mode='depth')`
So I change `mode='depth'` to `mode='pose'` ,and the result shows 12 numbers.
What do they mean respectively?

**Comment by kristijanbartol** [comment]
They represent 2 6DoF vectors. You probably use FLAGS.seq_length=3, therefore you have 2 pose estimations. Pose-net outputs it in this format and you can directly create pose matrix from it (http://ksimek.github.io/2012/08/22/extrinsic/).

**Comment by kristijanbartol** [comment]
@goeatsmall Absolutely, I'm currently working on this project for my Master's so I could probably help you. :) My email is kristijan.bartol@gmail.com if you prefer emails.

**Comment by kristijanbartol** [comment]
@goeatsmall Hey, I misread your question, sorry. To estimate pose, you can just feed images (in sequence of FLAGS.seq_length) into pose_exp function and you will get seq_length - 1 DoF vectors. No need for intrinsics matrix.
