### ISSUE TITLE
Depth and Pose on Image with Black Borders

### ISSUE THREAD

**Issue by gilmartinspinheiro** [tinghuiz/SfMLearner#88]
Hi. First of all, thanks for sharing your code!

My question is, do you think the black borders on an image like this will affect the depth and pose training/predictions?

![exemplo](https://user-images.githubusercontent.com/33527319/41500234-e935c198-7185-11e8-81a3-13f72937703f.jpg)

**Comment by tinghuiz** [comment]
It's hard to say without trying. The depth values around the black borders will be wrong, but the central region might still be okay. The pose prediction should be less affected.

**Comment by tinghuiz** [comment]
Feel free to post further updates on this issue. I'm curious to see what effects it could cause.
