### ISSUE TITLE
KITTI testing pose

### ISSUE THREAD

**Issue by marianlonga** [tinghuiz/SfMLearner#89]
Hi, I have succesfully trained the model and got depth predictions but I'm having a problem getting the pose predictions using the command
`python test_kitti_pose.py --test_seq 9 --dataset_dir /scratch/local/ssd/mlonga/kitti_raw/ --output_dir /scratch/local/ssd/mlonga/kitti_pose_output_seq_9/ --ckpt_file /scratch/local/ssd/mlonga/checkpoints/model.latest`
Here's the traceback:
`Traceback (most recent call last):
  File "test_kitti_pose.py", line 97, in <module>
    main()
  File "test_kitti_pose.py", line 71, in main
    with open(FLAGS.dataset_dir + 'sequences/%.2d/times.txt' % FLAGS.test_seq, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/local/ssd/mlonga/kitti_raw/sequences/09/times.txt'`
I think I'm using an incorrect dataset_dir since it doesn't anywhere contain the file times.txt. I've also tried using the directory with processed KITTI data and also tried downloading the KITTI odometry ground truth poses (http://www.cvlibs.net/download.php?file=data_odometry_poses.zip), but none of these contain times.txt. Does anyone know how to solve the problem? Thanks!

**Comment by tinghuiz** [comment]
For the pose experiments, you need to download the KITTI odometry set (instead of the raw data): http://www.cvlibs.net/datasets/kitti/eval_odometry.php.

**Comment by marianlonga** [comment]
Ok thanks!
