### ISSUE TITLE
OutOfRangeError

### ISSUE THREAD

**Issue by dtborders** [tinghuiz/SfMLearner#91]
Hi All, 
I am trying to use this code for depth estimation in biomedical imaging. I seem to have run into a strange error. 
I am running this code on a google cloud instance of a p100 gpu with CUDA 9.0 and python 3.5 installed. 
The model starts training, then after a couple thousand iterations, it throws this error. I processed my biomedical imaging data the same way the KITTI data was processed. 

Thanks!
Daniel Borders 

[terminalOutput .txt](https://github.com/tinghuiz/SfMLearner/files/2292636/terminalOutput.txt)

**Comment by ali28729** [comment]
Were you able to find the cause of this exception and any solution for it?
