### ISSUE TITLE
problem when testing posenet?

### ISSUE THREAD

**Issue by LinRui9531** [tinghuiz/SfMLearner#94]
Hi,@tinghuiz 
I want to train posenet on KITTI data_odometry_color. And i got the trianed net. BUT when i testing , the problem as following: 
**InvaildArugmentError: Assign requires shapes of both tensors to match. lhs shape=[7,7,15,16], rhs shape=[7,7,9,16].**  

But it didn't exist on your posenet. 
Whether if you train posenet or save it independly?

**Comment by Huang-Jin** [comment]
I guess I know the reason. The data you input is generated with sequence length 5 while the model is trained with sequence length 3. So the shape is not consistent. So you may need to change the sequence length in test_pose.py.

**Comment by LinRui9531** [comment]
@Huang-Jin Ohh, thank you. It's unconsistent sequence length that cause it.

**Comment by tinghuiz** [comment]
@Huang-Jin I used kitti_odometry because that's the official KITTI split for odometry benchmarking.
