### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory 

### ISSUE THREAD

**Issue by lixiangyu-1008** [tinghuiz/SfMLearner#95]
when I run the test_kitti_depth.py  I encounter a issue :
Traceback (most recent call last):
  File "test_kitti_depth.py", line 66, in <module>
    tf.app.run()
  File "/home/lli/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test_kitti_depth.py", line 48, in main
    fh = open(test_files[idx], 'rb')
IsADirectoryError: [Errno 21] Is a directory: '/home/lli/tensorflow/SfMLearner/data/kitti/'

I run the .py as  
python test_kitti_depth.py --dataset_dir=/home/lli/tensorflow/SfMLearner/data/kitti/  --output_dir=/home/lli/tensorflow/SfMLearner/output --ckpt_file=/home/lli/tensorflow/SfMLearner/models/model-190532

**Comment by lixiangyu-1008** [comment]
@Huang-Jin @tinghuiz

**Comment by Huang-Jin** [comment]
It's a little strange. I haven't encountered such problem.
Maybe the reason is that the program finds nothing in test_files_eigen.txt.
And then the variable test_files contains only the dataset_dir.
I think this problem could be dealt with by debug.

**Comment by lixiangyu-1008** [comment]
thank you! I will try.
