### ISSUE TITLE
Question about the ground truth depth of kitti dataset

### ISSUE THREAD

**Issue by Huang-Jin** [tinghuiz/SfMLearner#97]
Hello, @tinghuiz 
  Recently, I want to see the predicted depth and the ground truth depth. So I write some codes to do this work. But I find that the ground truth depth generated are very coarse. Is there any problem in my codes (main codes pasted below)?

Here is one of results I see, the rightest one is the predicted ground truth depth.
![sample](https://user-images.githubusercontent.com/24383733/47081687-f7fa1580-d23d-11e8-8b78-3a4b934ed853.png)

```
def main():
    pred_depths = np.load(args.pred_file)
    test_files = read_text_lines(args.test_file_list)
    gt_files, gt_calib, im_sizes, im_files, cams = \
        read_file_data(test_files, args.kitti_dir)
    num_test = len(im_files)
    fig, ax = plt.subplots(1,3)
    plt.ion()
    for t_id in range(num_test):
        camera_id = cams[t_id]  # 2 is left, 3 is right
        pred_depth = cv2.resize(pred_depths[t_id], (im_sizes[t_id][1], im_sizes[t_id][0]),
                                interpolation=cv2.INTER_LINEAR)
        gt_depth = generate_depth_map(gt_calib[t_id],
                                      gt_files[t_id],
                                      im_sizes[t_id],
                                      camera_id,
                                      False,
                                      True)

        mask = np.logical_and(gt_depth > args.min_depth,
                              gt_depth < args.max_depth)
        # crop used by Garg ECCV16 to reprocude Eigen NIPS14 results
        # if used on gt_size 370x1224 produces a crop of [-218, -3, 44, 1180]
        gt_height, gt_width = gt_depth.shape
        crop = np.array([0.40810811 * gt_height, 0.99189189 * gt_height,
                         0.03594771 * gt_width, 0.96405229 * gt_width]).astype(np.int32)

        crop_mask = np.zeros(mask.shape)
        crop_mask[crop[0]:crop[1], crop[2]:crop[3]] = 1
        mask = np.logical_and(mask, crop_mask)

        # Scale matching
        scalor = np.median(gt_depth[mask]) / np.median(pred_depth[mask])
        pred_depth[mask] *= scalor

        pred_depth[pred_depth < args.min_depth] = args.min_depth
        pred_depth[pred_depth > args.max_depth] = args.max_depth

        # show the original image, predicted depth and ground truth depth
        image = misc.imread(im_files[t_id])
        ax[0].imshow(image)
        ax[1].imshow(normalize_depth_for_display(pred_depth))
        ax[2].imshow(normalize_depth_for_display(gt_depth))

        plt.show()

        input()
```

**Comment by Huang-Jin** [comment]
Does this problem happened because that kitti doesn't have the ground truth depth?

**Comment by Huang-Jin** [comment]
Also, there are many strange black points in the predicted ground truth. Why does it occur?

**Comment by tinghuiz** [comment]
KITTI only has sparse ground-truth from the laser scanner. I'm not sure why your prediction has black points.

**Comment by Huang-Jin** [comment]
Ok, thank you for your reply.
I asked this question because I find that the images pasted in the paper of Geonet seems to have ground truth depth with one of the image from KITTI (pasted below). Maybe I need to ask the author of Geonet.

![sample](https://user-images.githubusercontent.com/24383733/47142383-5afab380-d2f5-11e8-8fbc-c09e9b3fdb12.png)

In addition, I find that those black points are related to codes which generates mask. It  scaled the pred_depth and so those areas are not consistent with their neighbors.
